### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#10]
hello, a question, how can I make with kether a system that has 2 conditions but only needs one?

example i create a level system for a network and i want to add that if you have the level.premium permission then you can get the vip rewards if not the default ones and inside vip and default they will have to fulfill x conditions.

**Comment by CPJiNan** [comment]
Hello, @Zarkness

Please try using if-else statements within a single condition, for example:

![Example](https://github.com/user-attachments/assets/df0b3bd3-07b4-4264-83bb-3091620cae5a)

```
      - |
        if permission level.premium then {
          true
        } else if all [ permission level.default1 permission level.default2 permission level.default3 ] then {
          true
        }
```

The "all" statement checks if all the conditions in the action list return true.

**Comment by Zarkness** [comment]
ok, now I try it and the if all instead of going in 1 line can also go like the other one?

**Comment by CPJiNan** [comment]
If you mean using multiple conditions with if-else statements, yes, it is possible. 

For example:
```
    Condition:
      - |
        if permission level.premium1 then {
          true
        } else if all [ permission level.default1 permission level.default2 permission level.default3 ] then {
          true
        }
      - |
        if permission level.premium2 then {
          true
        } else if all [ permission level.default4 permission level.default5 permission level.default6 ] then {
          true
        }
```
This allows you to combine multiple conditions and handle them with if-else logic.

**Comment by Zarkness** [comment]
but having it that way does not oblige to comply with the 2 instead of 1 or the other?

**Comment by Zarkness** [comment]
the thing is that setting it that way sends me a message saying “maximum level of dralor reached!”

**Comment by Zarkness** [comment]
> @Zarkness If you mean using multiple conditions with if-else statements, yes, it is possible.
> 
> For example:
> 
> ```
>     Condition:
>       - |
>         if permission level.premium1 then {
>           true
>         } else if all [ permission level.default1 permission level.default2 permission level.default3 ] then {
>           true
>         }
>       - |
>         if permission level.premium2 then {
>           true
>         } else if all [ permission level.default4 permission level.default5 permission level.default6 ] then {
>           true
>         }
> ```
> 
> This allows you to combine multiple conditions and handle them with if-else logic.
> 
> Only when both conditions following "- |" return true will it be considered as meeting the condition.

this way it forces me to have both permissions and I want you to pass either having level.premium1 together with its conditions or level.premium2 and its conditions

**Comment by Zarkness** [comment]
what I want is like the if & else in programming, something like this, that only happens if the if x or if y is fulfilled.

```java

if x {
conditions
....
} else if y {
condition s
...
}

```

**Comment by CPJiNan** [comment]
You can try multiple if-else statements. For example:
```
if permission level.condition1 then {
   if condition1 then {
      true
   } else false
} else if permission level.condition2 then {
   if condition1 then {
      true
   } else false
}
```

**Comment by Zarkness** [comment]
it does allow me to use one or the other, but if I add a message in any field it does not come out.

**Comment by CPJiNan** [comment]
@Zarkness 
The following statements might help you:

## Nested if-else
**Example:**
``` yaml
    Condition:
      - |
        if permission level.premium then {
          if xxx then {
            true
          } else {
            false
          }
        } else {
          if xxx then {
            true
          } else {
            false
          }
        }
```

## all
Checks if all the actions in the list return true.
**Usage:** all {action list}
**Example:**
``` kether
all [ player op player sneaking ]
all [ permission userA permission userB permission userC ]
```
## any
Checks if any of the actions in the list return true.
**Usage:** any {action list}
**Example:**
``` kether
any [ player op player sneaking ]
any [ permission userA permission userB permission userC ]
```

These examples may help you set up the conditions you need.

**Comment by Zarkness** [comment]
okey thx
