### ISSUE TITLE
原版经验值不增加

### ISSUE THREAD

**Issue by xiaoshuaixia2012** [CPJiNan/AkariLevel#13]
当我装上这个插件时，获取经验球mc原版的经验值就不会增加，卸载插件就恢复正常，这是怎么回事？

**Comment by CPJiNan** [comment]
感谢使用 AkariLevel 。

取消原版经验变更是为了避免影响插件等级在原版经验条上的显示。这个功能是可以关闭的，以下是两种不同的修改方式，请根据您的需要选择。

① 如果您不打算将 AkariLevel 等级组的经验进度在原版经验条上显示，并且想让原版等级与插件独立。请修改 settings.yml 中 Trace 下的 Vanilla 为 true 。同时在 level 文件夹中所有等级组配置的 Trace 下 Condition 列表加一行 - false 。

② 如果您想让原版经验计算在某个等级组的经验构成中，请打开 level 文件夹中对应等级组的配置文件，在 Source 下的 Subscribe 列表中加入一行 - VANILLA_EXP_CHANGE 。这样设置的话，当玩家获得原版经验时，订阅该经验来源的等级组经验也会增加。

如果您仍然存有疑问，可以考虑加群 704109949 寻求帮助。或者阅读插件文档 https://cpjinan.github.io/Wiki/

**Comment by xiaoshuaixia2012** [comment]
谢谢了，才发现是旧版有bug我没更新
