### ISSUE TITLE
add message for translate

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#19]
there are messages that are not to translate, for example the message when you put /akarilevel and it shows you all the commands of the plugin

add autocomplete for all parameters of all plugin commands, also add a help for /akarilevel exp and /akarilevel level, make the plugin 100% translatable, at least what the user sees from inside the game either admin or user.

**Comment by CPJiNan** [comment]
I'm sorry that I don't quite understand what you mean.
Could you please provide a screenshot to help me better understand your issue?

**Comment by Zarkness** [comment]
one of the things I mean is to be able to translate this message. 

then another thing I also say is that when I put only the command /akarilevel exp or /akarilevel level that like the /akarilevel has a message explaining each command the same but for level, exp, data.


what I mean about the autocomplete is that when I put /akarilevel exp <playername> <system exp name> <quantity> <argument {silent etc... }> does not autocomplete the arguments and the same for the level command or if the /akarilevel exp command has an argument as the plugin wiki says it does not autocomplete them and the last thing I said was to check if there is any message other than that that the user sees from within minecraft and not from console either staff or a player on the server then put so that it is translatable.

![image](https://github.com/user-attachments/assets/22794068-5dd6-4d90-8df3-d37613c5f62b)

![image](https://github.com/user-attachments/assets/3a2cd21f-13c2-4d61-8864-64cb44fe47ee)

**Comment by CPJiNan** [comment]
@Zarkness 

Like this？All text in this command help including hover text is editable.
And language files can be reloaded by using `/akarilevel reload` command now.
![插件展示-1](https://github.com/user-attachments/assets/4b72133d-6c2e-4c2e-9f74-ef6e54b7fa57)
![插件展示-2](https://github.com/user-attachments/assets/b2d7c5a2-4a4e-4462-ab03-65a54d8163bc)

**Comment by Zarkness** [comment]
don't close the issue for the moment, I don't have time now to test and tell you in 5 or 6 hours I'll get home, try it and let you know.

**Comment by CPJiNan** [comment]
Besides, here is a machine translation version of plugin docs.

# Command parameters
## Command parameter format:

-k -k v -k=v --key --key value --key=value

(where k and key are parameter names, v and value are parameter values)


/akarilevel exp
    · silent - Close command prompt
    · source - PlayerExpChangeEvent Experience Source
/akarilevel exp add
    · sourceCheck - Check if the specified experience source is in the level group subscription source list
    · toAllLevelGroup - Change the level group parameter for the operation given by this experience from the specified level group to all level groups (with source check)
        
/akarilevel level
    · silent - Close command prompt
    · noAction - Modify the level without executing the corresponding Kether action for the level
    · source - PlayerLevelChangeEvent Level Source
    
/akarilevel trace
    · silent - Close command prompt

For example:
`/akarilevel exp add PlayerName Example 100 --source=VANILLA_EXP_CHANGE --sourceCheck`

This command will check if the Example level group is subscribed to the `Experience Source.VANILLA_EXP_CHANGE`

If the specified source is in the subscription list, the player's PlayerName is added 100 points of experience for the Example level group. Otherwise, the experience-given action will not be performed.

**Comment by Zarkness** [comment]
From what I'm looking at it seems to me that what you did is to configure the commands I do not mean to configure the commands if not rather the message that sends when you put /akarilevel like other plugins allows you to edit the help message of the plugin as this equal.

So if the message was the one below, then add in the en_US.yml that message for the command /akarilevel.

```yml
Usage: /akarilevel
   ├─ level
   │   ├─ add <player> <levelGroup> <amount> [<options>]
   │   ├─ remove <player> <levelGroup> <amount> [<options>]
   │   ├─ set <player> <levelGroup> <amount> [<options>]
   │   ├─ check <player> <levelGroup>
   │   ├─ levelup [<levelGroup>]
   │   └─ trace [<levelGroup>] [<options>]
   ├─ exp
   │   ├─ add <player> <levelGroup> <amount> [<options>]
   │   ├─ remove <player> <levelGroup> <amount> [<options>]
   │   ├─ set <player> <levelGroup> <amount> [<options>]
   │   └─ check <player> <levelGroup>
   ├─ data
   │   ├─ get <table> <index> <key>
   │   ├─ set <table> <index> <key> <value>
   │   ├─ reset <table> <index> <key>
   │   └─ save
   └─ reload
```

From what I'm looking at it seems to me that what you did is to configure the commands I do not mean to configure the commands if not rather the message that sends when you put /akarilevel like other plugins allows you to edit the help message of the plugin as this equal.

So if the message was the one below, then add in the en_US.yml that message for the command /akarilevel.


it should be something like this link https://paste.helpch.at/vupetewiwa.py

because being able to translate but not edit how the message is seen is a bit ugly, because in the format that you did you can translate language and little more you can not catch, translate, improve and put to taste of each person the message that is what I was saying from the beginning and the message help: , level-help: exp-help:, data-help, it is not that you add the command help if not that when you put and execute only the commands /akarilevel, /akarilevel level, /akarilevel exp, /akarilevel data because it sends you that message of help. 

if there is something that you don't understand before launching yourself like crazy to do it first tell me, I try to explain it to you again and when you manage to understand it if it seems to you well and you like it then you start to do it.

**Comment by Zarkness** [comment]
> Besides, here is a machine translation version of plugin docs.
> 
> # Command parameters
> Command parameter format:
> 
> `-k -k v -k=v --key --key value --key=value`
> 
> (where k and key are parameter names, v and value are parameter values)
> 
> ```
> /akarilevel exp
>     · silent - Close command prompt
>     · source - PlayerExpChangeEvent Experience Source
> /akarilevel exp add
>     · sourceCheck - Check if the specified experience source is in the level group subscription source list
>     · toAllLevelGroup - Change the level group parameter for the operation given by this experience from the specified level group to all level groups (with source check)
>         
> /akarilevel level
>     · silent - Close command prompt
>     · noAction - Modify the level without executing the corresponding Kether action for the level
>     · source - PlayerLevelChangeEvent Level Source
>     
> /akarilevel trace
>     · silent - Close command prompt
> ```
> 
> For example: `/akarilevel exp add PlayerName Example 100 --source=VANILLA_EXP_CHANGE --sourceCheck`
> 
> This command will check if the Example level group is subscribed to the Experience Source.`VANILLA_EXP_CHANGE`
> 
> If the specified source is in the subscription list, the player's PlayerName is added 100 points of experience for the Example level group. Otherwise, the experience-given action will not be performed.

and about this I know how it works but what I was saying is to add that when you can put any of these parameters so that you get to autocomplete just as you get to autocomplete data, exp, etc ... that is if the command /akarilevel exp add <player> <level name> <quantity> {parameters}, so that {parameters} comes out to autocomplete, currently does not come out to autocomplete that part when you are writing the command.

I ask you please that if there is any part that you do not understand very well that you ask me before you start doing it, because then you end up doing what I said.

**Comment by Zarkness** [comment]
I'm using the latest version and if the lang something has `[]` it deletes it instead of showing it look at the video, the `[]` doesn't show them if you put `[[[]]][][][][][][][] instead of showing this message `&8[&3Akari&bLevel&8] [[]][][][]][&bInfo &8| &6Plugin reloaded. ` shows `&3Akari&bLevel` as if you hadn't put anything in the lang but the plugin name, which before you updated adding that you added the command_en_US. yml that is not very useful, in fact what I was asking for is the previous message, before if you could put `[]` you should remove that from command_en_US.yml and do it as I said in the previous commit because it allows to customize more the message that is what I suggested.

https://github.com/user-attachments/assets/b432c539-b4aa-4b29-b5ff-8044f113d3f6

**Comment by CPJiNan** [comment]
The command help in the following image is automatically generated by the created Helper () function of the Taboolib framework based on the command structure, and I cannot modify its style.

What you want me to do is add something in the language file that allows the use of something like TabooLib Components (https://taboolib.feishu.cn/wiki/Gp8ywJfMEi7UIgkUFLZc1mi5nvh) to provide command help for the main command and each sub-command, right?


![image](https://github.com/user-attachments/assets/ac657518-3d5e-4702-a009-6cc8b4c1f1f5)

**Comment by Zarkness** [comment]
> The command help in the following image is automatically generated by the createHelper() function of the Taboolib framework based on the command structure, and I cannot modify its style.
> 
I was already looking that it is generated automatically by taboolib, and you could not now that you have the message that taboolib generates add it in the en_US.yml and send that message? and there is not a way to do that when you create the help add it in the language file as shown in the game and then use the language file? because what I like is to customize the messages to 100%, give them my touch even in the help command.

> What you want me to do is add something in the language file that allows the use of something like TabooLib Components (https://taboolib.feishu.cn/wiki/Gp8ywJfMEi7UIgkUFLZc1mi5nvh) to provide command help for the main command and each sub-command, right?
> 
> ![image](https://private-user-images.githubusercontent.com/103565669/395854218-ac657518-3d5e-4702-a009-6cc8b4c1f1f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjAxMzcsIm5iZiI6MTczNDI1OTgzNywicGF0aCI6Ii8xMDM1NjU2NjkvMzk1ODU0MjE4LWFjNjU3NTE4LTNkNWUtNDcwMi1hMDA5LTZjYzhiNGMxZjFmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMDUwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODk5OWEzZmU1NzRhMjdlMjJkY2RkZWYzNTkxMjViYzFhMzQxMWQ3NmE5ZmQ3MWZhNDYwOGFlMTI4YmQ4MDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4osXdSFZzZfshOOx_vIcQbx3G4-f-5CqS2O1_iFkwps)

Then the taboolib components if the hover and all that can also be done without the json format with a shorter format as minimessage and other forms that has minimessage `<hover:show_text:'<red>test'>TEST` and if you want to add suggest command or execute command to the message would only be to do it like this
` <click:run_command:'/command'><hover:show_text:'text'>hello</hover></click>.` 
` <click:suggest_command:'/command'><hover:show_text:'text'>asd</hover></click>.` 
If I mean that

https://docs.advntr.dev/minimessage/format.html#hover

I don't know if you have discord but if you do and you prefer we can talk faster over there send soli if you have it this is my id: zarkness

**Comment by Zarkness** [comment]
> I'm using the latest version and if the lang something has `[]` it deletes it instead of showing it look at the video, the `[]` doesn't show them if you put `[[[]]][][][][][][][]` instead of showing this message `&8[&3Akari&bLevel&8] [[]][][][]][&bInfo &8| &6Plugin reloaded.` shows `&3Akari&bLevel` as if you had not put anything in the lang but the name of the plugin, thing that before you updated adding that you added the command_en_US.yml that is not very useful, that in if what I was asking is the previous message that is if the message help looked the way I told you then put that same text in the en_US. yml and that people can translate it and change it to their liking for example maybe I do not want to use `├─` and prefer to use `⬜` and then to make the text hover, you add support for minimessage and people could create hovers, clickable and everything that allows you minimessage, not like you did, before if you could put `[]` you should remove that command_en_US. yml and do it as I said in the previous commit because it allows to customize more the message which is what I suggested.
> 
> **I repeat if you do not understand something of the message that I send you before you start to do anything ask me and I will answer you, but do not start to do things like that as crazy as you did.**
> 
>  Code_S3s3Bm4qoS.mp4

by the way don't forget this

**Comment by CPJiNan** [comment]
> by the way don't forget this

I realized that might be because I enabled Language.enableSimpleComponent, which allows you to use []() TabooLib Components within language files. However, correspondingly, we need to escape the general [], like \[\].

Regarding this issue, I might modify the default language files in the next version. 

Additionally, I have added your Discord. Please accept the friend request.

**Comment by Zarkness** [comment]
I answer you by discord otherwise the issue becomes very long and I usually answer faster by discord.
