### ISSUE TITLE
关于经验系统的一点小小建议

### ISSUE THREAD

**Issue by liangcha385** [CPJiNan/AkariLevel#2]
想要可以根据玩家权限情况来选择当前显示的是原版经验系统还是插件经验系统的效果

_感觉好异想天开_

**Comment by CPJiNan** [comment]
感谢建议！

在4.0版本中，您可以使用新增的等级组功能来同时管理多个等级系统。该功能允许您为每个等级组设置追踪条件，以便您在多个等级组之间进行自由切换。

需要注意的是，4.0版本的数据结构可能与3.x有很大不同，请您在安装新版本前备份玩家数据以防数据丢失。

**Comment by CPJiNan** [comment]
感谢您的建议！

在4.0版本中，您可以使用新增的等级组功能来设置不同的等级体系。该功能允许您为每个等级组设置追踪条件，以便您在多个等级组之间进行自由切换。

需要注意的是，4.0版本的数据结构可能与3.x有很大不同，请您在安装新版本前备份玩家数据以防数据丢失。

**Comment by CPJiNan** [comment]
感谢您的建议！

在4.0版本中，您可以使用新增的等级组功能来管理不同的等级系统。该功能允许您为每个等级组设置追踪条件，以便您在多个等级组之间进行自由切换。

需要注意的是，4.0版本的数据结构可能与3.x有很大不同，请您在安装新版本前备份玩家数据以防数据丢失。
