### ISSUE TITLE
Feature Request: Support for Multiple Level Systems

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#5]
I would like to request a feature that allows the creation of multiple, distinct level systems within the plugin. Each level system should be able to have a unique name for easy differentiation and management. This feature would greatly enhance the flexibility and usability of the plugin, especially for servers with multiple game modes or role-specific level systems.

**Proposed Functionality:**

**Multiple Level Systems:**

Implement functionality to support the creation and management of multiple level systems.
Each level system should be independent, with its own set of levels, experience requirements, and rewards.

**Named Level Systems:**

Allow each level system to be assigned a unique name.
These names should be used for referencing and managing the level systems within configuration files and in-game commands.

**In-Game Commands:**

Introduce new or updated commands to interact with the different level systems.
Commands should include options to specify which level system to interact with based on its name.

**Benefits:**

This feature will allow server administrators to create more complex and varied gameplay experiences by utilizing multiple, named level systems.
It provides clear organization and separation of different leveling systems, reducing potential confusion and management overhead.

**Comment by Zarkness** [comment]
in addition to the above add support in the level.yml for & together with hex colors and gradients, as currently you have to use §

**Comment by CPJiNan** [comment]
Thank you for your advice.
It may be adopted in the following version.

**Comment by CPJiNan** [comment]
Hello!

Thank you for your suggestion.

The Multiple Level Systems feature has been basically completed and will be released in version 4.0. Here is a snapshot of version 4.0 (currently available only in Simplified Chinese). 

Please note that the data structure of version 4.0 is significantly different from 3.x, so make sure to back up your previous player data before installation to prevent any data loss.
