### ISSUE TITLE
Feature: add customizable message condition

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#8]
add that the message when you set a condition or you can't go up a level can be customizable for each level.

**Comment by Zarkness** [comment]
add that the message when you receive exp to use the display instead of the one you are currently using.

Since for when the name takes space to use the current one is ugly because in my case Paradox_Hierarchy instead of Paradox Hierarchy that is the display, besides it would be nice to be able to edit that message by level system.

I have to use the command /akarilevel exp add %player_name% <levelname> <exp points>, because in the lobby is the only way I can give them xp.

**Comment by CPJiNan** [comment]
It seems you might want to use the display name of the level groups instead of their edit names in these messages.

![Lang](https://github.com/CPJiNan/AkariLevel/assets/103565669/fa26dfdc-a450-43b0-9145-5aeaddeae14f)

In the latest build, the default language files have been changed. Please regenerate them or refer to [this](https://github.com/CPJiNan/AkariLevel/blob/master/src/main/resources/lang/en_US.yml) to avoid variable confusion in the messages.

**Comment by CPJiNan** [comment]
Additionally, you might want to use hex colors in the lang files. TabooLib Components might help solve your issue.

Here is an example:

`example-json:
  ==: JSON
  text: '你好，朋友！感谢您使用 [&9&nTabooLib Components] 复合文本!'
  args:
    - url: 'https://plugins.ptms.ink/function/components/'`

[Example](https://taboolib.feishu.cn/d7786f5b-b3c2-4077-9297-1f171fa9880a)

For colors, you can use codes like &9&l or &{#FF0000}. These are not shown here for brevity.

**Comment by CPJiNan** [comment]
Additionally, you might want to use hex colors in the lang files. TabooLib Components might help solve your issue.

Here is an example:

```
example-json:
  ==: JSON
  text: '你好，朋友！感谢您使用 [&9&nTabooLib Components] 复合文本!'
  args:
    - url: 'https://plugins.ptms.ink/function/components/'
```

![Example](https://github.com/CPJiNan/AkariLevel/assets/103565669/acba6259-98dc-4548-b8aa-ca40ba83c318)

> For colors, you can use codes like &9&l or &{#FF0000}. These are not shown here for brevity.

**Comment by Zarkness** [comment]
> add that the message when you receive exp to use the display instead of the one you are currently using.
> 
> Since for when the name takes space to use the current one is ugly because in my case Paradox_Hierarchy instead of Paradox Hierarchy that is the display, besides it would be nice to be able to edit that message by level system.
> 
> I have to use the command /akarilevel exp add %player_name% , because in the lobby is the only way I can give them xp.

Okay, and this? @CPJiNan

**Comment by Zarkness** [comment]
I just found that the maximum experience is 2147483647, is it possible to increase the limit?

**Comment by CPJiNan** [comment]
> I just found that the maximum experience is 2147483647, is it possible to increase the limit?
> 
> 
> 
> it would also be nice to be able to use advanced formulas

The variable type for level and experience has been changed from Int to Long in the latest build

**Comment by CPJiNan** [comment]
> I just found that the maximum experience is 2147483647, is it possible to increase the limit?
> 
> 
> 
> it would also be nice to be able to use advanced formulas

The variable type for level and experience has been changed from Int to Long in the latest build.

**Comment by CPJiNan** [comment]
Regarding your request to "separately check if different conditions are met and execute different actions," here is an example:

![Example-1](https://github.com/CPJiNan/AkariLevel/assets/103565669/44172edd-1500-4c4a-91c7-347cd9495710)

![Example-2](https://github.com/CPJiNan/AkariLevel/assets/103565669/d4aecd6f-7924-41b2-ac72-f942471a5f45)

The "Condition" config item will evaluate the Kether script and check its return values. This allows you to use if-else statements to send messages to players based on the conditions.

**Comment by CPJiNan** [comment]
Regarding your request to "separately check if different conditions are met and execute different actions," here is an example:

![Example-1](https://github.com/CPJiNan/AkariLevel/assets/103565669/44172edd-1500-4c4a-91c7-347cd9495710)

![Example-2](https://github.com/CPJiNan/AkariLevel/assets/103565669/94ca92d3-0bd5-40a3-b87f-17bea51f50a2)

The "Condition" config item will evaluate the Kether script and check its return values. This allows you to use if-else statements to send messages to players based on the conditions.

**Comment by Zarkness** [comment]
> > I just found that the maximum experience is 2147483647, is it possible to increase the limit?
> > it would also be nice to be able to use advanced formulas
> 
> The variable type for level and experience has been changed from Int to Long in the latest build.

okey, thx

**Comment by Zarkness** [comment]
> Regarding your request to "separately check if different conditions are met and execute different actions," here is an example:
> 
> ![Example-1](https://private-user-images.githubusercontent.com/103565669/344447060-44172edd-1500-4c4a-91c7-347cd9495710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MDYwLTQ0MTcyZWRkLTE1MDAtNGM0YS05MWM3LTM0N2NkOTQ5NTcxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzk4NmY2YzhkMTMxZjNjY2IwMmY2ZDM2Y2NhZWIxMzBmOWUzODAzOTBjNTdiMDRkOWRkZjY0OGQxZTNjZjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0faAdt2cDceTVNlGOQxcwvBm7srS5IUKQ3P13rh12IU)
> 
> ![Example-2](https://private-user-images.githubusercontent.com/103565669/344447247-94ca92d3-0bd5-40a3-b87f-17bea51f50a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MjQ3LTk0Y2E5MmQzLTBiZDUtNDBhMy1iODdmLTE3YmVhNTFmNTBhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjlhOWRkZjVjYmZkYTYzZWI1ZWRjN2IwN2U2MWUzODBmY2M3NmU3MDQ0Yjc1ZDE1NmM5YjIxMWJmYTY1YjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.25Wqt1VltAqVhT7DpqhGZJ00mOLGrrWnXuiCas5NqLE)
> 
> The "Condition" config item will evaluate the Kether script and check its return values. This allows you to use if-else statements to send messages to players based on the conditions.

ok and with that it does not send me the message of the en_US file that I told you about? the levelup-fail

**Comment by Zarkness** [comment]
is that already added or not yet? I just tried it and it doesn't work.

![image](https://github.com/CPJiNan/AkariLevel/assets/48263644/0c6d1de0-86c7-411e-9cf0-5e9ebc5e415c)

**Comment by Zarkness** [comment]
I don't know how to do the math but I have this formula for level 5 `Exp: "20 / %level% + 100 * 2"` and the result it gives is 

![image](https://github.com/CPJiNan/AkariLevel/assets/48263644/9e06be69-c783-4b7a-a988-e3413107ce18)

**Comment by CPJiNan** [comment]
> > Regarding your request to "separately check if different conditions are met and execute different actions," here is an example:
> 
> > 
> 
> > ![Example-1](https://private-user-images.githubusercontent.com/103565669/344447060-44172edd-1500-4c4a-91c7-347cd9495710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MDYwLTQ0MTcyZWRkLTE1MDAtNGM0YS05MWM3LTM0N2NkOTQ5NTcxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzk4NmY2YzhkMTMxZjNjY2IwMmY2ZDM2Y2NhZWIxMzBmOWUzODAzOTBjNTdiMDRkOWRkZjY0OGQxZTNjZjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0faAdt2cDceTVNlGOQxcwvBm7srS5IUKQ3P13rh12IU)
> 
> > 
> 
> > ![Example-2](https://private-user-images.githubusercontent.com/103565669/344447247-94ca92d3-0bd5-40a3-b87f-17bea51f50a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MjQ3LTk0Y2E5MmQzLTBiZDUtNDBhMy1iODdmLTE3YmVhNTFmNTBhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjlhOWRkZjVjYmZkYTYzZWI1ZWRjN2IwN2U2MWUzODBmY2M3NmU3MDQ0Yjc1ZDE1NmM5YjIxMWJmYTY1YjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.25Wqt1VltAqVhT7DpqhGZJ00mOLGrrWnXuiCas5NqLE)
> 
> > 
> 
> > The "Condition" config item will evaluate the Kether script and check its return values. This allows you to use if-else statements to send messages to players based on the conditions.
> 
> 
> 
> ok and with that it does not send me the message of the en_US file that I told you about? the levelup-fail

It seems that your experience formula rather than the upgrade condition is the problem. When using the default formula, it seems that the custom message can be received normally.

**Comment by Zarkness** [comment]
> > > Regarding your request to "separately check if different conditions are met and execute different actions," here is an example:
> > 
> > 
> > > 
> > 
> > 
> > > ![Example-1](https://private-user-images.githubusercontent.com/103565669/344447060-44172edd-1500-4c4a-91c7-347cd9495710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MDYwLTQ0MTcyZWRkLTE1MDAtNGM0YS05MWM3LTM0N2NkOTQ5NTcxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzk4NmY2YzhkMTMxZjNjY2IwMmY2ZDM2Y2NhZWIxMzBmOWUzODAzOTBjNTdiMDRkOWRkZjY0OGQxZTNjZjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0faAdt2cDceTVNlGOQxcwvBm7srS5IUKQ3P13rh12IU)
> > 
> > 
> > > 
> > 
> > 
> > > ![Example-2](https://private-user-images.githubusercontent.com/103565669/344447247-94ca92d3-0bd5-40a3-b87f-17bea51f50a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzODcsIm5iZiI6MTcxOTczMzA4NywicGF0aCI6Ii8xMDM1NjU2NjkvMzQ0NDQ3MjQ3LTk0Y2E5MmQzLTBiZDUtNDBhMy1iODdmLTE3YmVhNTFmNTBhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjlhOWRkZjVjYmZkYTYzZWI1ZWRjN2IwN2U2MWUzODBmY2M3NmU3MDQ0Yjc1ZDE1NmM5YjIxMWJmYTY1YjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.25Wqt1VltAqVhT7DpqhGZJ00mOLGrrWnXuiCas5NqLE)
> > 
> > 
> > > 
> > 
> > 
> > > The "Condition" config item will evaluate the Kether script and check its return values. This allows you to use if-else statements to send messages to players based on the conditions.
> > 
> > 
> > ok and with that it does not send me the message of the en_US file that I told you about? the levelup-fail
> 
> I tested using almost the same configuration as yours, and it seems that your experience formula rather than the upgrade condition is the problem.
> 
> When using the default formula, it seems that the custom message can be received normally.

if I was testing and if it seems to be problem the formula since for example if I put a formula in which it gives decimals is where the problem is since for example this formula (100 * 2 ) * (21 / 7) gave me well osea 600, but if I change 7 by 8 or %level% and gives me the value of the image that you pass before, as it gives decimals and gives error and then when you level up having this formula (100 * 2 ) * (21 / %level%) does not update well and does not allow level up even if you have 10000000000 exp points.

**Comment by CPJiNan** [comment]
It seems that the decimal point in your calculated result is missing. 

Maybe you can try the JavaScript parseInt() function. 

As for the sin value, I think you can try Math.sin().

**Comment by Zarkness** [comment]
then how should be the formula using javascript and math.sin()?

**Comment by CPJiNan** [comment]
> then how should be the formula using javascript and math.sin()?

Maybe you can try the JavaScript Number.toFixed() function. 

For example:

``` javascript
(12.5).toFixed()
```

As for the sin value, I think you can try Math.sin().

``` javascript
(Math.sin(1)*100).toFixed()
```

**Comment by Zarkness** [comment]
ok, thank you very much, I will try the last snapshot with all this, and if I find any problem, I will let you know.

by the way the command to give exp the maximum that it allows to put is 1000000000 and now the limit of exp is greater, it would not be his serious that it allows to put the maximum that if I am not mistaken it is 9223372036854775807

**Comment by CPJiNan** [comment]
> ok, thank you very much, I will try the last snapshot with all this, and if I find any problem, I will let you know.
> 
> by the way the command to give exp the maximum that it allows to put is 1000000000 and now the limit of exp is greater, it would not be his serious that it allows to put the maximum that if I am not mistaken it is 9223372036854775807

It has been fixed in the latest build.

**Comment by Zarkness** [comment]
okey, thx

**Comment by CPJiNan** [comment]
> okey, thx, then you can close the issue, so if you want anything else I will open another issue, by the way where is the repo of the wiki to help with the translation etc ...

OK. 

Here is the repository: https://github.com/CPJiNan/Wiki, and here is the plugin documentation: https://cpjinan.github.io/Wiki/. 

I would greatly appreciate it if you could help with the translation.
